name: Publish Docs

on:
  push:
    branches: [main]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    name: Docs builder and publisher
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          pip install pip-tools
          python -m piptools compile --resolver=backtracking --extra=docs -o requirements.txt pyproject.toml
          pip install -r requirements.txt
      - name: Install Gdstk
        run: python setup.py install --user
      - name: Build docs
        run: sphinx-build docs docs/_build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
          publish_branch: gh-pages
          keep_files: false
          force_orphan: true
